version: '3.1'


services:

  tomcat-dev:
    build:
      context: .
      dockerfile: ./docker/tomcat.Dockerfile
    image: ricejamesh/tomcat-dev
    ports:
      - '8080:8080'
    volumes:
      - tomcat-dev:/catalina-base/logs

  postgres-dev:
    image: postgres:9.4
    restart: always
    volumes: 
      - postgres-dev:/var/lib/postgresql
    ports:
      - '5432:5432'
    secrets:
      - psql_user
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER_FILE: /run/secrets/psql_user

secrets:
  psql_user:
    file: ./docker/psql_user.txt
  psql_password:
    file: ./docker/psql_password.txt


volumes:
  postgres-dev:
  tomcat-dev:
